name: Adlist generator

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      filter-url:
        required: true
        type: string
      address:
        type: string

jobs:
  adlist:
    runs-on: ubuntu-latest
    steps:
      - name: Download filter
        run: wget -qO filter.txt "${{ inputs.filter-url }}"
      - name: Generate hosts
        run: |
          sed -nE \
            's/^\|\|([0-9a-z]+([-.][0-9a-z]+)+)\^\s*/${{ case(inputs.address == '::', '::', '0.0.0.0') }} \1/p' \
            filter.txt > "${{ inputs.name }}.txt" \
            && echo "::notice::$(awk 'END {print NR}' '${{ inputs.name }}.txt') hosts added"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.name }}.txt
