name: Adlist
run-name: ${{ github.actor }} is generating adlists

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Adguard adlist
        run: |
          wget -q https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt \
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: .
