name: GitHub pages

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  adguard:
    uses: alexey-tsarkov/mikrotik-scripts/.github/workflows/adlist.yml@main
    with:
      name: adguard
      filter-url: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt

  easylist:
    uses: alexey-tsarkov/mikrotik-scripts/.github/workflows/adlist.yml@main
    with:
      name: easylist
      filter-url: https://easylist.to/easylist/easylist.txt

  easyprivacy:
    uses: alexey-tsarkov/mikrotik-scripts/.github/workflows/adlist.yml@main
    with:
      name: easyprivacy
      filter-url: https://easylist.to/easylist/easyprivacy.txt

  pages:
    needs: [adguard, easylist, easyprivacy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: adguard
      - uses: actions/download-artifact@v5
        with:
          name: easylist
      - uses: actions/download-artifact@v5
        with:
          name: easyprivacy
      - uses: actions/upload-pages-artifact@v4
        with:
          path:
